In [1]:
import time
import tqdm
import math
import logging
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import train_test_split
from sklearn.metrics import auc, accuracy_score, mean_squared_error, pairwise_distances_argmin_min, confusion_matrix
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb



from new_jmlm import JMLM
from load_data import load_data

dataset = "bridge"
X_train, X_test, y_train, y_test = load_data(dataset)

print(X_train.shape)



(4912, 7)


## MLP

In [2]:
clf = MLPClassifier(random_state=1, max_iter=300).fit(X_train, y_train)

print(clf.predict_proba(X_test[:1]))

print(clf.predict(X_test[:5, :]))

print(clf.score(X_test, y_test))

[[0.16723665 0.05536353 0.21323694 0.53600568 0.01431765]]
[[0 0 0 1 0]
 [0 0 1 0 0]
 [0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 1 0]]
0.4030944625407166


d:\Applications\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(


## Random Forest

In [3]:
clf = RandomForestClassifier(max_depth=500, random_state=0)

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

acc = accuracy_score(y_test, y_pred)

print(f'Prediction Accuracy: {acc}')

Prediction Accuracy: 0.4780130293159609


## XGBoost

In [4]:
X_train, X_test, y_train, y_test = load_data(dataset, onehot=False)

xgb_model = xgb.XGBClassifier(objective="multi:softprob", random_state=42)

xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
acc = accuracy_score(y_test, y_pred)
print(f'Prediction Accuracy: {acc}')

[[ 59   4  61  70   1]
 [  3  86  10  44   0]
 [ 18   6 221 104   1]
 [ 17  37  65 365   0]
 [  3   2   9  17  25]]
Prediction Accuracy: 0.6156351791530945
